# Cameron Holmes
## Week 12 - 4/7/2022
### Python Numpy Universal Functions

In [1]:
import numpy as np
arr = np.arange(21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [2]:
# sqrt
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [8]:
#randn
arr1 = np.random.randn(10) #Return a sample from the "standard normal" distribution.
arr1

array([ 0.62039634, -0.70924095, -0.35413117,  0.15101399, -0.0060441 ,
        1.19881707,  0.24618184,  0.06937074, -0.04762768,  0.51465078])

In [9]:
arr2 = np.random.randn(10)
arr2

array([-0.46427024, -0.3653086 , -0.79866453,  0.83753451, -0.48775161,
       -0.37694208,  0.94439576, -1.80397912, -0.66113832, -0.58709589])

In [10]:
#add
np.add(arr1,arr2)

array([ 0.1561261 , -1.07454955, -1.1527957 ,  0.9885485 , -0.49379571,
        0.82187499,  1.1905776 , -1.73460838, -0.70876601, -0.07244511])

In [11]:
#maximum
np.maximum(arr1,arr2)

array([ 0.62039634, -0.3653086 , -0.35413117,  0.83753451, -0.0060441 ,
        1.19881707,  0.94439576,  0.06937074, -0.04762768,  0.51465078])

In [13]:
arr1 = np.arange(9).reshape((3,3))
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
arr2 = np.ones(9).reshape((3,3))
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.add(arr1,arr2)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [17]:
# Array Filtering
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
print(arr < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [19]:
# Replace values of an array, using where
np.where(arr<4, True, False)

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [20]:
#np.where(cond,x,y) Return elements chosen from 'x' or 'y' depending on 'condition'
np.where(arr < 4, -1, -2)

array([[-1, -1, -1],
       [-1, -2, -2],
       [-2, -2, -2]])

In [21]:
np.where((arr < 4) & (arr > 2), -1,-2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [23]:
#Where with 1-D
arr1 = np.array([1,2,3,4,5])
arr2 = arr1*10
arr_b = np.array([True,False,True,True,False])

print(arr1)
print(arr2)
print(arr_b)

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]


In [24]:
#zip
zip(arr1,arr2,arr_b)

In [25]:
list(zip(arr1,arr2,arr_b))

[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, True), (5, 50, False)]

In [26]:
# using list comprehension
arr3 = [r1 if b else r2 for r1,r2,b in zip(arr1,arr2,arr_b)]
arr3

[1, 20, 3, 4, 50]

In [27]:
# using np.where
arr3 = np.where(arr_b, arr1,arr2)
arr3

array([ 1, 20,  3,  4, 50])

In [29]:
# using where with 2-D array
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
cond = np.array([[True,False],[True,False]])

print("arr1: ", arr1, end="\n\n")
print("arr2: ", arr2, end="\n\n")
print("cond: ", cond, end="\n\n")

arr1:  [[1 2]
 [3 4]]

arr2:  [[5 6]
 [7 8]]

cond:  [[ True False]
 [ True False]]



In [30]:
np.where(cond,arr1,arr2)

array([[1, 6],
       [3, 8]])

In [32]:
np.where([[True,False],[True,False]], [[5,6],[7,8]], [[1,2],[3,4]])

array([[5, 2],
       [7, 4]])

In [34]:
# a short use of randn
from numpy.random import randn
arr = randn(3,3)
arr

array([[-0.25370211, -1.49964148,  0.18953581],
       [-1.70933304, -0.50022849, -0.49542718],
       [ 1.38572178, -1.09570123,  1.1170359 ]])

In [35]:
np.where(arr<0, 0, arr)

array([[0.        , 0.        , 0.18953581],
       [0.        , 0.        , 0.        ],
       [1.38572178, 0.        , 1.1170359 ]])

In [36]:
# boolean arrays
# any
arr_b = np.array([True,False,True,False,False])
arr_b.any() #Returns True if any of the elements of 'a' evaluate to True

True

In [37]:
#all
arr_b.all() #Returns True if all elements evaluate to True

False

In [39]:
# unique()
# Find unique elements of an array
fruits = np.array(['Apple','Cherry','Apple','Orange','Cherry','Banana'])
np.unique(fruits)

array(['Apple', 'Banana', 'Cherry', 'Orange'], dtype='<U6')

In [40]:
#in1d
#Test whether each element of a 1d array is also present in a second array.
np.in1d(['Apple','Cherry','Grape'],fruits)

array([ True,  True, False])